version: '3.8'
services:
  smartcity-waste-management:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: smartcity
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
