
services:

  db:
    container_name: postgres_db
    image: "postgres:15"
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: smartcity
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password

  smartcity-waste-management:
    container_name: smart_city_api
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DBP_HOST=db
      - DBP_PORT=5432
      - DBP_NAME=smartcity
      - DBP_ADMIN=root
      - DBP_PASSWORD=password