-- Criação da tabela TB_USUARIO
CREATE TABLE TB_USUARIO (
    ID_USUARIO VARCHAR(20) NOT NULL,
    NM_USUARIO VARCHAR(50) NOT NULL,
    DS_EMAIL VARCHAR(50) NOT NULL,
    NR_CPF VARCHAR(14) NOT NULL,
    DT_NASC DATE NOT NULL,
    CONSTRAINT PK_TB_USUARIO PRIMARY KEY (ID_USUARIO),
    CONSTRAINT UN_TB_NR_CPF UNIQUE (NR_CPF)
);

-- Criação da tabela TB_AGENDAMENTO
CREATE TABLE TB_AGENDAMENTO (
    ID_AGENDA VARCHAR(20) NOT NULL,
    DT_AGENDA DATE NOT NULL,
    HR_AGENDA TIMESTAMP NOT NULL,
    END_COLETA VARCHAR(50) NOT NULL,
    DS_OBS VARCHAR(80),
    CONSTRAINT PK_TB_AGENDAMENTO PRIMARY KEY (ID_AGENDA)
);

-- Criação da tabela TB_MOTORISTA
CREATE TABLE TB_MOTORISTA (
    ID_MOTORISTA VARCHAR(20) NOT NULL,
    NM_MOTORISTA VARCHAR(50) NOT NULL,
    CPF_MOTORISTA VARCHAR(14) NOT NULL,
    CNH_MOTORISTA NUMERIC(11, 0) NOT NULL,
    CNH_CATEGORIA VARCHAR(3) NOT NULL,
    STATUS_MOTORISTA VARCHAR(10) DEFAULT 'DISPONIVEL' CHECK (STATUS_MOTORISTA IN ('DISPONIVEL', 'OCUPADO')),
    CONSTRAINT PK_TB_MOTORISTA PRIMARY KEY (ID_MOTORISTA)
);

-- Criação da tabela TB_CAMINHAO
CREATE TABLE TB_CAMINHAO (
    ID_CAMINHAO VARCHAR(20) NOT NULL,
    NM_PLACA VARCHAR(7) NOT NULL,
    KG_CAPACIDADE NUMERIC(20, 2) NOT NULL,
    EST_ORIGEM VARCHAR(2) NOT NULL,
    CONSTRAINT PK_TB_CAMINHAO PRIMARY KEY (ID_CAMINHAO)
);

-- Criação da tabela TB_COLETA
CREATE TABLE TB_COLETA (
    ID_COLETA VARCHAR(20) NOT NULL,
    KG_COLETA NUMERIC(20, 2) NOT NULL,
    DT_COLETA DATE NOT NULL,
    HR_COLETA TIMESTAMP NOT NULL,
    ID_MOTORISTA VARCHAR(20),
    ID_CAMINHAO VARCHAR(20),
    CONSTRAINT PK_TB_COLETA PRIMARY KEY (ID_COLETA),
    CONSTRAINT FK_COLETA_MOTORISTA FOREIGN KEY (ID_MOTORISTA) REFERENCES TB_MOTORISTA(ID_MOTORISTA),
    CONSTRAINT FK_COLETA_CAMINHAO FOREIGN KEY (ID_CAMINHAO) REFERENCES TB_CAMINHAO(ID_CAMINHAO)
);

-- Criação da tabela TB_ROTA
CREATE TABLE TB_ROTA (
    ID_ROTA VARCHAR(20) NOT NULL,
    END_ORIGEM VARCHAR(50) NOT NULL,
    END_DESTINO VARCHAR(50) NOT NULL,
    DSC_ROTA VARCHAR(80) NOT NULL,
    HR_PREVISAO TIMESTAMP NOT NULL,
    CONSTRAINT PK_TB_ROTA PRIMARY KEY (ID_ROTA)
);
