CREATE TABLE TB_USUARIO (
    ID_USUARIO VARCHAR2(20) NOT NULL,
    NM_USUARIO VARCHAR2(50) NOT NULL,
    DS_EMAIL VARCHAR2(50) NOT NULL,
    NR_CPF VARCHAR2(14) NOT NULL,
    DT_NASC DATE NOT NULL,
    CONSTRAINT PK_TB_USUARIO PRIMARY KEY (ID_USUARIO),
    CONSTRAINT UN_TB_NR_CPF UNIQUE (NR_CPF)
);

CREATE TABLE TB_AGENDAMENTO (
    ID_AGENDA VARCHAR2(20) NOT NULL,
    DT_AGENDA DATE NOT NULL,
    HR_AGENDA TIMESTAMP NOT NULL,
    END_COLETA VARCHAR2(50) NOT NULL,
    DS_OBS VARCHAR2(80) NULL,
    CONSTRAINT PK_TB_AGENDAMENTO PRIMARY KEY (ID_AGENDA)
);

CREATE TABLE TB_COLETA (
    ID_COLETA VARCHAR2(20) NOT NULL,
    KG_COLETA NUMBER(20) NOT NULL,
    DT_COLETA DATE NOT NULL,
    HR_COLETA TIMESTAMP NOT NULL,
    ID_MOTORISTA VARCHAR2(20),
    ID_CAMINHAO VARCHAR2(20),
    CONSTRAINT PK_TB_COLETA PRIMARY KEY (ID_COLETA),
    CONSTRAINT FK_COLETA_MOTORISTA FOREIGN KEY (ID_MOTORISTA) REFERENCES TB_MOTORISTA(ID_MOTORISTA),
    CONSTRAINT FK_COLETA_CAMINHAO FOREIGN KEY (ID_CAMINHAO) REFERENCES TB_CAMINHAO(ID_CAMINHAO)
);

CREATE TABLE TB_ROTA (
    ID_ROTA VARCHAR2(20) NOT NULL,
    END_ORIGEM VARCHAR2(50) NOT NULL,
    END_DESTINO VARCHAR2(50) NOT NULL,
    DSC_ROTA VARCHAR2(80) NOT NULL,
    HR_PREVISAO TIMESTAMP NOT NULL,
    CONSTRAINT PK_TB_ROTA PRIMARY KEY (ID_ROTA)
);

CREATE TABLE TB_MOTORISTA (
    ID_MOTORISTA VARCHAR2(20) NOT NULL,
    NM_MOTORISTA VARCHAR2(50) NOT NULL,
    CPF_MOTORISTA VARCHAR2(14) NOT NULL,
    CNH_MOTORISTA NUMBER(11) NOT NULL,
    CNH_CATEGORIA VARCHAR2(3) NOT NULL,
    STATUS_MOTORISTA VARCHAR2(10) DEFAULT 'DISPONIVEL' CHECK (STATUS_MOTORISTA IN ('DISPONIVEL', 'OCUPADO')),
    CONSTRAINT PK_TB_MOTORISTA PRIMARY KEY (ID_MOTORISTA)
);

CREATE TABLE TB_CAMINHAO (
    ID_CAMINHAO VARCHAR2(20) NOT NULL,
    NM_PLACA VARCHAR2(7) NOT NULL,
    KG_CAPACIDADE NUMBER(20) NOT NULL,
    EST_ORIGEM VARCHAR2(2) NOT NULL,
    CONSTRAINT PK_TB_CAMINHAO PRIMARY KEY (ID_CAMINHAO)
);

